function formatDuration(elapsedMs = 0) { const seconds = Math.max(0, Math.ceil(elapsedMs / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }

class SingleBoardRenderer {
  constructor(canvas) { this.canvas = canvas; this.ctx = canvas.getContext("2d"); this.level = null; this.controls = {}; this.resize(); }
  resize() {
    const info = wx.getWindowInfo(); this.width = info.windowWidth; this.height = info.windowHeight; this.dpr = Math.min(info.pixelRatio || 1, 3);
    this.canvas.width = Math.round(this.width * this.dpr); this.canvas.height = Math.round(this.height * this.dpr); if (this.ctx.setTransform) this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0); else this.ctx.scale(this.dpr, this.dpr);
  }
  setLevel(level) { this.level = level; }
  layout() {
    const size = this.level.rows; const headerClearance = 88; const rowHeight = 34; const controlGap = 16; const outerBorder = 8;
    const controlHeight = outerBorder + controlGap + rowHeight * 4 + controlGap * 3; const bottomClearance = 12;
    const maxBoardHeight = this.height - headerClearance - controlHeight - bottomClearance;
    const cell = Math.max(1, Math.floor(Math.min((this.width - 38) / size, maxBoardHeight / size)));
    const width = cell * size; const minTop = headerClearance; const maxTop = Math.max(minTop, this.height - width - controlHeight - bottomClearance);
    const top = Math.max(minTop, Math.min(Math.round((this.height - width) / 2) - 24, maxTop));
    return { cell, width, left: Math.round((this.width - width) / 2), top, controlGap, rowHeight, outerBorder };
  }
  rounded(x, y, width, height, radius, fill, stroke) {
    const c = this.ctx; const r = Math.max(0, Math.min(radius, width / 2, height / 2)); c.beginPath();
    if (!r || !c.quadraticCurveTo) c.rect(x, y, width, height);
    else { c.moveTo(x + r, y); c.lineTo(x + width - r, y); c.quadraticCurveTo(x + width, y, x + width, y + r); c.lineTo(x + width, y + height - r); c.quadraticCurveTo(x + width, y + height, x + width - r, y + height); c.lineTo(x + r, y + height); c.quadraticCurveTo(x, y + height, x, y + height - r); c.lineTo(x, y + r); c.quadraticCurveTo(x, y, x + r, y); }
    if (fill) { c.fillStyle = fill; c.fill(); } if (stroke) { c.strokeStyle = stroke; c.stroke(); }
  }
  render(snapshot, view) {
    const c = this.ctx; c.clearRect(0, 0, this.width, this.height); this.drawSky(); this.drawHeader(snapshot, view); this.drawBoard(snapshot); this.drawControls(snapshot, view);
    if (view.completionVisible) this.drawCompletion(snapshot, view); else if (view.clockSetupVisible) this.drawClockSetup(view); else if (view.clockEnded) this.drawClockResult(view);
  }
  drawSky() { const c = this.ctx; c.fillStyle = "#67C8F4"; c.fillRect(0, 0, this.width, this.height); c.fillStyle = "rgba(255,255,255,.8)"; [[42,105,34],[this.width-58,140,28],[this.width*.26, this.height-108,30]].forEach(([x,y,r]) => { c.beginPath(); c.arc(x,y,r,0,Math.PI*2); c.arc(x+r*.75,y+5,r*.7,0,Math.PI*2); c.arc(x-r*.75,y+7,r*.65,0,Math.PI*2); c.fill(); }); }
  drawHeader(snapshot, view) {
    const c = this.ctx, headerY = 32, statsY = headerY + 62, title = view.clockActive ? `时间挑战 ${view.clockTier.label}` : `${view.difficultyLabel} ${this.level.gridSize}`;
    this.rounded(18, headerY, 112, 30, 14, view.clockActive ? "#ffe2a6" : "#fff4be", "#b94232"); c.fillStyle = "#7b321e"; c.font = "700 12px sans-serif"; c.textAlign = "center"; c.fillText(title, 74, headerY + 20);
    c.fillStyle = "#fff"; c.font = "700 17px Microsoft YaHei, sans-serif"; c.fillText(view.clockActive ? `⏱ ${view.time}  ·  ${view.clockSolved} 局` : `◷ ${view.time}   Points: ${view.points}`, this.width / 2, statsY);
    this.controls.sound = { x: this.width - 75, y: headerY, width: 58, height: 30 }; this.rounded(this.controls.sound.x, headerY, 58, 30, 14, view.sound ? "#ffd43b" : "#fff4be", "#7b321e"); c.fillStyle = "#7b321e"; c.font = "700 11px sans-serif"; c.fillText(`音效 ${view.sound ? "开" : "关"}`, this.width - 46, headerY + 20); c.textAlign = "left";
  }
  drawBoard(snapshot) {
    const c = this.ctx, box = this.layout(), level = this.level; this.board = box; this.rounded(box.left-8, box.top-8, box.width+16, box.width+16, 14, "#fff4be", "#b94232"); c.strokeStyle = "rgba(123,50,30,.3)"; c.lineWidth = 1;
    for (let index=0; index<=level.rows; index+=1) { c.beginPath(); c.moveTo(box.left, box.top+index*box.cell); c.lineTo(box.left+box.width, box.top+index*box.cell); c.stroke(); c.beginPath(); c.moveTo(box.left+index*box.cell, box.top); c.lineTo(box.left+index*box.cell, box.top+box.width); c.stroke(); }
    c.strokeStyle="#7b4a2a";c.lineWidth=Math.max(3,box.cell*.08);(level.walls||[]).forEach((wall)=>{const [direction,rowText,colText]=wall.split("_");const row=Number(rowText),col=Number(colText);c.beginPath();if(direction==="H"){const y=box.top+(row+1)*box.cell;c.moveTo(box.left+col*box.cell+box.cell*.14,y);c.lineTo(box.left+(col+1)*box.cell-box.cell*.14,y);}else{const x=box.left+(col+1)*box.cell;c.moveTo(x,box.top+row*box.cell+box.cell*.14);c.lineTo(x,box.top+(row+1)*box.cell-box.cell*.14);}c.stroke();});
    if(snapshot.path.length){const start=snapshot.path[0],end=snapshot.path[snapshot.path.length-1],startX=box.left+(start.col+.5)*box.cell,startY=box.top+(start.row+.5)*box.cell,endX=box.left+(end.col+.5)*box.cell,endY=box.top+(end.row+.5)*box.cell;const gradient=c.createLinearGradient?.(startX,startY,endX||startX+1,endY||startY+1);if(gradient?.addColorStop){gradient.addColorStop(0,"#0e9f57");gradient.addColorStop(.5,"#2fe278");gradient.addColorStop(1,"#087f46");c.strokeStyle=gradient;}else c.strokeStyle="#20c96b";c.lineWidth=Math.max(14,box.cell*.38);c.lineCap="round";c.lineJoin="round";c.beginPath();snapshot.path.forEach((cell,index)=>{const x=box.left+(cell.col+.5)*box.cell,y=box.top+(cell.row+.5)*box.cell;if(index)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke();}
    level.waypoints.forEach((point)=>{const x=box.left+(point.cell.col+.5)*box.cell,y=box.top+(point.cell.row+.5)*box.cell; c.fillStyle="#111"; c.font=`700 ${Math.max(12,box.cell*.25)}px Microsoft YaHei, sans-serif`; c.textAlign="center"; c.textBaseline="middle"; c.fillText(String(point.number),x,y);}); c.textAlign="left"; c.textBaseline="alphabetic";
  }
  drawControls(snapshot, view) {
    const c=this.ctx,total=Math.min(this.width-36,360),left=(this.width-total)/2,gap=8,h=this.board.rowHeight,verticalGap=this.board.controlGap,top=this.board.top+this.board.width+this.board.outerBorder+verticalGap,buttonFill="#fff",textColor="#111",border="#3f2a20",selectedBorder="#d94d3f"; c.lineWidth=2;
    const button=(id,label,x,y,width,selected=false)=>{this.controls[id]={x,y,width,height:h};this.rounded(x,y,width,h,8,buttonFill,selected?selectedBorder:border);c.fillStyle=textColor;c.font="700 12px Microsoft YaHei, sans-serif";c.textAlign="center";c.fillText(label,x+width/2,y+22);};
    const two=(total-gap)/2; button("undo","↶ 撤回",left,top,two); button("reset","⌫ 清空",left+two+gap,top,two);
    const difficultyRow=top+h+verticalGap; this.controls.difficulties=[]; ["简单","中等","困难"].forEach((label,index)=>{const width=(total-gap*2)/3,x=left+index*(width+gap),selected=view.difficulty===["easy","medium","hard"][index];this.controls.difficulties.push({x,y:difficultyRow,width,height:h,id:["easy","medium","hard"][index]});this.rounded(x,difficultyRow,width,h,8,buttonFill,selected?selectedBorder:border);c.fillStyle=textColor;c.font="700 12px Microsoft YaHei, sans-serif";c.textAlign="center";c.fillText(label,x+width/2,difficultyRow+22);});
    const sizeRow=difficultyRow+h+verticalGap; this.controls.sizes=[]; ["6x6","8x8","10x10","12x12"].forEach((label,index)=>{const width=(total-gap*3)/4,x=left+index*(width+gap),selected=view.gridSize===label;this.controls.sizes.push({x,y:sizeRow,width,height:h,id:label});this.rounded(x,sizeRow,width,h,8,buttonFill,selected?selectedBorder:border);c.fillStyle=textColor;c.font="700 12px Microsoft YaHei, sans-serif";c.fillText(label,x+width/2,sizeRow+22);});
    const clockRow=sizeRow+h+verticalGap; this.controls.clock={x:left,y:clockRow,width:total,height:h};this.rounded(left,clockRow,total,h,9,"#35a853","#176b46");c.fillStyle="#fff";c.font="700 13px Microsoft YaHei, sans-serif";c.fillText("⏱ 时间挑战  Beat the Clock",left+total/2,clockRow+22);c.textAlign="left";
  }
  modalFrame(height) { const w=Math.min(this.width-40,340),x=(this.width-w)/2,y=Math.max(92,(this.height-height)/2); const c=this.ctx; c.fillStyle="rgba(9,54,86,.72)";c.fillRect(0,0,this.width,this.height);this.rounded(x,y,w,height,18,"#fffdf8","#b94232");return {x,y,w,height}; }
  drawClockSetup(view) {
    const c=this.ctx,frame=this.modalFrame(292),{x,y,w}=frame; this.controls.clockTiers=[];this.controls.clockCancel={x:x+w-38,y:y+12,width:26,height:26};this.rounded(this.controls.clockCancel.x,this.controls.clockCancel.y,26,26,13,"#f2f0ec");c.fillStyle="#73706a";c.font="700 19px sans-serif";c.textAlign="center";c.fillText("×",x+w-25,y+31);c.fillStyle="#25313a";c.font="italic 700 25px serif";c.fillText("Beat the Clock",this.width/2,y+58);c.fillStyle="#717a7f";c.font="12px sans-serif";c.fillText("60秒内尽可能多完成棋盘，每局 +8秒",this.width/2,y+82);const gap=7,tierW=(w-32-gap*3)/4,tierY=y+105;view.clockTiers.forEach((tier,index)=>{const tx=x+16+index*(tierW+gap);this.controls.clockTiers.push({x:tx,y:tierY,width:tierW,height:80,id:tier.id});this.rounded(tx,tierY,tierW,80,9,"#fff","#d6d0c8");c.fillStyle="#26333b";c.font="700 12px serif";c.fillText(tier.label,tx+tierW/2,tierY+25);c.fillStyle="#e36a3e";c.font="700 11px sans-serif";c.fillText("+8 秒",tx+tierW/2,tierY+47);c.fillStyle="#717a7f";c.font="10px sans-serif";c.fillText(tier.gridSize,tx+tierW/2,tierY+66);});c.fillStyle="#35a853";this.rounded(x+18,y+210,w-36,38,9,"#35a853","#176b46");c.fillStyle="#fff";c.font="700 13px Microsoft YaHei, sans-serif";c.fillText("选择一个档位开始挑战",this.width/2,y+235);c.textAlign="left";
  }
  drawClockResult(view) {
    const c=this.ctx,frame=this.modalFrame(278),{x,y,w}=frame,result=view.clockResult||{},current=result.current||{solved:0,remainingMs:0},best=result.best||current; this.controls.clockLeaderboard={x:x+20,y:y+188,width:w-40,height:32};this.controls.clockRestart={x:x+20,y:y+228,width:w-40,height:34}; c.fillStyle="#fff1e8";c.beginPath();c.arc(this.width/2,y+36,22,0,Math.PI*2);c.fill();c.fillStyle="#e36a3e";c.font="700 23px serif";c.textAlign="center";c.fillText("⌛",this.width/2,y+44);c.fillStyle="#25313a";c.font="italic 700 25px serif";c.fillText("时间到！",this.width/2,y+79);c.fillStyle="#717a7f";c.font="12px sans-serif";c.fillText(`${result.tier?.label || ""}挑战 · 已完成 ${current.solved} 局 · 剩余 ${formatDuration(current.remainingMs)}`,this.width/2,y+103);this.rounded(x+24,y+120,w-48,48,10,"#f2f0ec");c.fillStyle="#e36a3e";c.font="700 18px serif";c.fillText(`${best.solved} 局`,this.width/2,y+143);c.fillStyle="#74706a";c.font="10px sans-serif";c.fillText("本地最佳成绩",this.width/2,y+159);c.fillStyle="#717a7f";c.font="11px sans-serif";c.fillText(view.rankings.global.text,this.width/2,y+183);this.rounded(this.controls.clockLeaderboard.x,this.controls.clockLeaderboard.y,this.controls.clockLeaderboard.width,32,9,"#fff","#d6d0c8");c.fillStyle="#303b40";c.font="700 12px sans-serif";c.fillText("查看时间挑战好友榜",this.width/2,y+209);this.rounded(this.controls.clockRestart.x,this.controls.clockRestart.y,this.controls.clockRestart.width,34,9,"#35a853","#176b46");c.fillStyle="#fff";c.font="700 12px Microsoft YaHei, sans-serif";c.fillText("再来一次",this.width/2,y+250);c.textAlign="left";
  }
  drawCompletion(snapshot, view) { const c=this.ctx,w=Math.min(this.width-40,340),h=332,x=(this.width-w)/2,y=Math.max(104,(this.height-h)/2),summary=view.completion,rankings=view.rankings; this.controls.completion={x,y,width:w,height:h}; c.fillStyle="rgba(9,54,86,.72)";c.fillRect(0,0,this.width,this.height);this.rounded(x,y,w,h,18,"#fffdf8","#b94232");this.controls.close={x:x+w-38,y:y+12,width:26,height:26};this.rounded(this.controls.close.x,this.controls.close.y,26,26,13,"#f2f0ec");c.fillStyle="#73706a";c.font="700 19px sans-serif";c.textAlign="center";c.fillText("×",this.controls.close.x+13,this.controls.close.y+19);c.fillStyle="#fff1e8";c.beginPath();c.arc(this.width/2,y+35,22,0,Math.PI*2);c.fill();c.fillStyle="#e36a3e";c.font="700 24px sans-serif";c.fillText("♕",this.width/2,y+43);c.fillStyle="#25313a";c.font="italic 700 26px serif";c.fillText("通关啦！",this.width/2,y+82);c.fillStyle="#7b7470";c.font="12px sans-serif";c.fillText("林径挑战完成",this.width/2,y+104);const cardTop=y+122,cardGap=8,cardW=(w-40-cardGap*2)/3,metric=[{value:view.time,label:"本局用时"},{value:formatDuration(summary.best.elapsedMs),label:"最佳成绩"},{value:String(summary.streak),label:"连续通关"}];metric.forEach((item,index)=>{const cx=x+20+index*(cardW+cardGap);this.rounded(cx,cardTop,cardW,58,10,"#f2f0ec");c.fillStyle="#e36a3e";c.font="700 18px serif";c.fillText(item.value,cx+cardW/2,cardTop+25);c.fillStyle="#74706a";c.font="10px sans-serif";c.fillText(item.label,cx+cardW/2,cardTop+45);});const actionHeight=34,actionInset=12,nextY=y+h-actionInset-actionHeight,leaderboardY=nextY-actionHeight-8,dividerY=leaderboardY-10;c.fillStyle="#2d3b43";c.font="700 13px sans-serif";c.fillText(rankings.friend.text,this.width/2,cardTop+88);c.fillStyle="#717a7f";c.font="11px sans-serif";c.fillText(rankings.global.text,this.width/2,cardTop+108);c.strokeStyle="#ddd8d2";c.lineWidth=1;c.beginPath();c.moveTo(x+24,dividerY);c.lineTo(x+w-24,dividerY);c.stroke();this.controls.leaderboard={x:x+22,y:leaderboardY,width:w-44,height:actionHeight};this.rounded(this.controls.leaderboard.x,this.controls.leaderboard.y,this.controls.leaderboard.width,actionHeight,9,"#fff","#d6d0c8");c.fillStyle="#303b40";c.font="700 12px sans-serif";c.fillText("查看排行榜",this.width/2,leaderboardY+22);this.controls.next={x:x+22,y:nextY,width:w-44,height:actionHeight};this.rounded(this.controls.next.x,this.controls.next.y,this.controls.next.width,actionHeight,9,"#35a853","#176b46");c.fillStyle="#fff";c.font="700 12px sans-serif";c.fillText("继续下一题",this.width/2,nextY+22);c.textAlign="left"; }
  toCell(point) { const b=this.board;if(!b||point.x<b.left||point.x>=b.left+b.width||point.y<b.top||point.y>=b.top+b.width)return null;return {row:Math.floor((point.y-b.top)/b.cell),col:Math.floor((point.x-b.left)/b.cell)}; }
  hit(box, point) { return box && point.x>=box.x && point.x<=box.x+box.width && point.y>=box.y && point.y<=box.y+box.height; }
}

module.exports = { SingleBoardRenderer };
