class SingleBoardRenderer {
  constructor(canvas) { this.canvas = canvas; this.ctx = canvas.getContext("2d"); this.level = null; this.controls = {}; this.resize(); }
  resize() {
    const info = wx.getWindowInfo(); this.width = info.windowWidth; this.height = info.windowHeight; this.dpr = Math.min(info.pixelRatio || 1, 3);
    this.canvas.width = Math.round(this.width * this.dpr); this.canvas.height = Math.round(this.height * this.dpr); if (this.ctx.setTransform) this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0); else this.ctx.scale(this.dpr, this.dpr); }
  setLevel(level) { this.level = level; }
  layout() {
    const size = this.level.rows; const top = 68; const footer = 154; const cell = Math.floor(Math.min((this.width - 38) / size, (this.height - top - footer) / size));
    const width = cell * size; return { cell, width, left: Math.round((this.width - width) / 2), top };
  }
  rounded(x, y, width, height, radius, fill, stroke) {
    const c = this.ctx; const r = Math.max(0, Math.min(radius, width / 2, height / 2)); c.beginPath();
    if (!r || !c.quadraticCurveTo) c.rect(x, y, width, height);
    else {
      c.moveTo(x + r, y); c.lineTo(x + width - r, y); c.quadraticCurveTo(x + width, y, x + width, y + r);
      c.lineTo(x + width, y + height - r); c.quadraticCurveTo(x + width, y + height, x + width - r, y + height);
      c.lineTo(x + r, y + height); c.quadraticCurveTo(x, y + height, x, y + height - r);
      c.lineTo(x, y + r); c.quadraticCurveTo(x, y, x + r, y);
    }
    if (fill) { c.fillStyle = fill; c.fill(); } if (stroke) { c.strokeStyle = stroke; c.stroke(); }
  }
  render(snapshot, view) {
    const c = this.ctx; c.clearRect(0, 0, this.width, this.height); this.drawSky(); this.drawHeader(snapshot, view); this.drawBoard(snapshot); this.drawControls(snapshot, view); if (snapshot.status === "completed") this.drawCompletion(snapshot, view); }
  drawSky() { const c = this.ctx; c.fillStyle = "#67C8F4"; c.fillRect(0, 0, this.width, this.height); c.fillStyle = "rgba(255,255,255,.8)"; [[42,105,34],[this.width-58,140,28],[this.width*.26, this.height-108,30]].forEach(([x,y,r]) => { c.beginPath(); c.arc(x,y,r,0,Math.PI*2); c.arc(x+r*.75,y+5,r*.7,0,Math.PI*2); c.arc(x-r*.75,y+7,r*.65,0,Math.PI*2); c.fill(); }); }
  drawHeader(snapshot, view) { const c = this.ctx; c.fillStyle = "#fff4be"; c.strokeStyle = "#b94232"; c.lineWidth = 2; this.rounded(18, 18, 102, 30, 14, "#fff4be", "#b94232"); c.fillStyle = "#7b321e"; c.font = "700 12px sans-serif"; c.textAlign = "center"; c.fillText(view.daily ? "每日挑战 8×8" : `${view.difficultyLabel} ${this.level.gridSize}`, 69, 38); c.fillStyle = "#fff"; c.font = "11px monospace"; c.fillText(`◷ ${view.time}   Points: ${view.points}`, this.width / 2, 38); this.controls.sound = { x: this.width - 75, y: 18, width: 58, height: 30 }; this.rounded(this.controls.sound.x, 18, 58, 30, 14, view.sound ? "#ffd43b" : "#fff4be", "#7b321e"); c.fillStyle = "#7b321e"; c.font = "700 11px sans-serif"; c.fillText(`音效 ${view.sound ? "开" : "关"}`, this.width - 46, 38); c.textAlign = "left"; }
  drawBoard(snapshot) { const c = this.ctx, box = this.layout(), level = this.level; this.board = box; this.rounded(box.left-8, box.top-8, box.width+16, box.width+16, 14, "#fff4be", "#b94232"); c.strokeStyle = "rgba(123,50,30,.3)"; c.lineWidth = 1; for (let index=0; index<=level.rows; index+=1) { c.beginPath(); c.moveTo(box.left, box.top+index*box.cell); c.lineTo(box.left+box.width, box.top+index*box.cell); c.stroke(); c.beginPath(); c.moveTo(box.left+index*box.cell, box.top); c.lineTo(box.left+index*box.cell, box.top+box.width); c.stroke(); }
    c.strokeStyle="#7b4a2a";c.lineWidth=Math.max(3,box.cell*.08);(level.walls||[]).forEach((wall)=>{const [direction,rowText,colText]=wall.split("_");const row=Number(rowText),col=Number(colText);c.beginPath();if(direction==="H"){const y=box.top+(row+1)*box.cell;c.moveTo(box.left+col*box.cell+box.cell*.14,y);c.lineTo(box.left+(col+1)*box.cell-box.cell*.14,y);}else{const x=box.left+(col+1)*box.cell;c.moveTo(x,box.top+row*box.cell+box.cell*.14);c.lineTo(x,box.top+(row+1)*box.cell-box.cell*.14);}c.stroke();});
    c.strokeStyle="#32b44a"; c.lineWidth=Math.max(6,box.cell*.14); c.lineCap="round"; if(snapshot.path.length){c.beginPath();snapshot.path.forEach((cell,index)=>{const x=box.left+(cell.col+.5)*box.cell,y=box.top+(cell.row+.5)*box.cell;if(index)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke();}
    level.waypoints.forEach((point)=>{const x=box.left+(point.cell.col+.5)*box.cell,y=box.top+(point.cell.row+.5)*box.cell; c.fillStyle="#111"; c.font=`700 ${Math.max(12,box.cell*.25)}px Microsoft YaHei, sans-serif`; c.textAlign="center"; c.textBaseline="middle"; c.fillText(String(point.number),x,y);}); c.textAlign="left"; c.textBaseline="alphabetic"; }
  drawControls(snapshot, view) { const c=this.ctx, total=Math.min(this.width-36,360),left=(this.width-total)/2,top=this.board.top+this.board.width+18,gap=8,h=34; const draw=(id,label,index,selected=false,disabled=false,count=3)=>{const width=(total-gap*(count-1))/count,x=left+index*(width+gap);this.controls[id]={x,y:top,width,height:h};this.rounded(x,top,width,h,8,disabled?"#d4cab0":selected?"#35a853":"#fff4be","#7b321e");c.fillStyle=selected?"#fff":"#7b321e";c.font="700 11px sans-serif";c.textAlign="center";c.fillText(label,x+width/2,top+22);}; draw("undo","↶ 撤回",0,false,!snapshot.path.length); draw("reset","⌫ 清空",1); draw("daily",view.dailyComplete?"每日挑战 ✓":"每日挑战",2,view.daily);
    const row=top+h+8; this.controls.difficulties=[]; ["简单","中等","困难"].forEach((label,index)=>{const width=(total-gap*2)/3,x=left+index*(width+gap);this.controls.difficulties.push({x,y:row,width,height:h,id:["easy","medium","hard"][index]});this.rounded(x,row,width,h,8,view.difficulty===this.controls.difficulties[index].id?"#d94d3f":"#fff4be","#7b321e");c.fillStyle=view.difficulty===this.controls.difficulties[index].id?"#fff":"#7b321e";c.fillText(label,x+width/2,row+22);});
    const sizeRow=row+h+8; this.controls.sizes=[]; ["6x6","8x8","10x10","12x12"].forEach((label,index)=>{const width=(total-gap*3)/4,x=left+index*(width+gap);this.controls.sizes.push({x,y:sizeRow,width,height:h,id:label});this.rounded(x,sizeRow,width,h,8,view.gridSize===label?"#d94d3f":"#fff4be","#7b321e");c.fillStyle=view.gridSize===label?"#fff":"#7b321e";c.fillText(label,x+width/2,sizeRow+22);}); c.textAlign="left"; }
  drawCompletion(snapshot, view) { const c=this.ctx,w=Math.min(this.width-44,330),h=174,x=(this.width-w)/2,y=(this.height-h)/2; c.fillStyle="rgba(9,54,86,.72)";c.fillRect(0,0,this.width,this.height);this.rounded(x,y,w,h,14,"#fff4be","#b94232");c.fillStyle="#b94232";c.font="700 10px monospace";c.textAlign="center";c.fillText(view.daily?"DAILY CHALLENGE COMPLETE":"TRAIL COMPLETE",this.width/2,y+34);c.fillStyle="#7b321e";c.font="700 24px sans-serif";c.fillText(view.daily?"今日林径已走通":"林径已走通",this.width/2,y+75);c.font="12px sans-serif";c.fillText(`${view.time} 用时  ·  ${view.points} 积分`,this.width/2,y+104);this.controls.next={x:x+28,y:y+122,width:w-56,height:34};this.rounded(this.controls.next.x,this.controls.next.y,this.controls.next.width,34,8,"#35a853","#176b46");c.fillStyle="#fff";c.font="700 12px sans-serif";c.fillText(view.daily?"返回随机题":"随机下一题",this.width/2,y+144);c.textAlign="left"; }
  toCell(point) { const b=this.board;if(!b||point.x<b.left||point.x>=b.left+b.width||point.y<b.top||point.y>=b.top+b.width)return null;return {row:Math.floor((point.y-b.top)/b.cell),col:Math.floor((point.x-b.left)/b.cell)}; }
  hit(box, point) { return box && point.x>=box.x && point.x<=box.x+box.width && point.y>=box.y && point.y<=box.y+box.height; }
}

module.exports = { SingleBoardRenderer };
