const assert = require("node:assert/strict");
const storage = new Map();
const noOp = () => undefined;
const context = { clearRect:noOp, fillRect:noOp, beginPath:noOp, arc:noOp, fill:noOp, stroke:noOp, moveTo:noOp, lineTo:noOp, quadraticCurveTo:noOp, fillText:noOp, setTransform:noOp, scale:noOp, set lineWidth(_){}, set lineCap(_){}, set strokeStyle(_){}, set fillStyle(_){}, set font(_){}, set textAlign(_){}, set textBaseline(_){} };
global.wx = { getWindowInfo: () => ({ windowWidth: 390, windowHeight: 844, pixelRatio: 1 }), getStorageSync: (key) => storage.get(key), setStorageSync: (key, value) => storage.set(key, value) };
const { ForestTrailMiniGame } = require("../core/GameFlow");
const sample = { id:"sample-6", title:"样例", gridSize:"6x6", difficulty:"easy", rows:6, cols:6, waypoints:[{number:1,cell:{row:0,col:0}},{number:2,cell:{row:5,col:5}}], walls:[], solution:Array.from({length:36},(_,index)=>({row:Math.floor(index/6),col:Math.floor(index/6)%2?5-index%6:index%6})) };
const canvas = { getContext: () => context };
const game = new ForestTrailMiniGame(canvas, [sample]);
assert.equal(game.current.id, "sample-6");
assert.equal(game.renderer.controls.sound.y, 32, "顶部状态栏应下移至32px");
assert.equal(game.renderer.controls.volume, undefined, "顶部不应再渲染音量调节按键");
assert.ok(game.renderer.board.top + game.renderer.board.width / 2 < 422, "棋盘应从竖屏中心上移并更靠近云朵");
assert.ok(game.renderer.board.top >= 88, "棋盘不得侵入下移后的顶部状态栏");
assert.equal(game.renderer.controls.difficulties[0].y - (game.renderer.controls.undo.y + game.renderer.controls.undo.height), game.renderer.board.controlGap);
assert.equal(game.renderer.controls.sizes[0].y - (game.renderer.controls.difficulties[0].y + game.renderer.controls.difficulties[0].height), game.renderer.board.controlGap);
let coinCount = 0; let ordinaryStepCount = 0; game.sound.coin = () => { coinCount += 1; }; game.sound.step = () => { ordinaryStepCount += 1; };
const toTouch = (cell) => ({ clientX: game.renderer.board.left + (cell.col + .5) * game.renderer.board.cell, clientY: game.renderer.board.top + (cell.row + .5) * game.renderer.board.cell });
game.handleStart({ touches:[toTouch({row:0,col:0})] });
game.handleMove({ touches:[toTouch({row:0,col:1})] });
assert.equal(coinCount, 1, "起点数字触达应播放一次金币音");
assert.equal(ordinaryStepCount, 0, "普通连线不得播放步进音效");
game.selectDaily(); assert.equal(game.mode, "daily"); assert.equal(game.current.gridSize, "8x8");
game.current.solution.forEach((cell) => game.engine.tryMove(cell));
assert.equal(game.progress.isDailyComplete(game.current), true);
game.handleStart({ touches:[{ clientX: game.renderer.controls.sound.x + 2, clientY: game.renderer.controls.sound.y + 2 }] });
assert.equal(game.progress.soundEnabled(), false);
console.log("原生单棋盘流程校验通过");
