const assert = require("node:assert/strict");
const started = [];
const makeOscillator = () => ({ frequency: { setValueAtTime() {}, exponentialRampToValueAtTime() {} }, connect() {}, start(at) { started.push(at); }, stop() {}, set type(_) {} });
const makeGain = () => ({ gain: { setValueAtTime() {}, exponentialRampToValueAtTime() {} }, connect() {} });
const backgroundEvents = [];
const backgroundMusic = { set src(value) { backgroundEvents.push(`src:${value}`); }, set autoplay(value) { backgroundEvents.push(`autoplay:${value}`); }, set loop(value) { backgroundEvents.push(`loop:${value}`); }, set volume(value) { backgroundEvents.push(`volume:${value}`); }, set obeyMuteSwitch(value) { backgroundEvents.push(`obeyMuteSwitch:${value}`); }, stop() { backgroundEvents.push("stop"); }, play() { backgroundEvents.push("play"); }, destroy() { backgroundEvents.push("destroy"); } };
global.wx = { createInnerAudioContext: () => backgroundMusic, createWebAudioContext: () => ({ currentTime: 0, destination: {}, resume() {}, createOscillator: makeOscillator, createGain: makeGain }) };
const { SoundFx } = require("../core/SoundFx");
const sound = new SoundFx(true); sound.startBackgroundMusic(); assert.deepEqual(backgroundEvents.slice(0, 6), ["src:audio/forest-trail-background.mp3", "autoplay:false", "loop:true", "volume:0.28", "obeyMuteSwitch:false", "play"], "背景音乐应以循环、低音量模式播放");
sound.step(); sound.tap(); sound.undo(); sound.reset(); sound.complete(); assert.equal(started.length, 0, "普通连线、按键、撤回、清空与通关均必须静音");
sound.coin(); assert.equal(started.length, 2, "数字触达应产生两层纸牌式短促音色"); assert.equal(backgroundEvents.filter((event) => event === "play").length, 1, "数字触达不得重启背景音乐");
sound.setEnabled(false); assert.equal(backgroundEvents.at(-1), "stop", "关闭音效开关应停止背景音乐"); const beforeMute = started.length; sound.coin(); assert.equal(started.length, beforeMute, "关闭音效后不得播放纸牌提示"); sound.setEnabled(true); assert.equal(backgroundEvents.at(-1), "play", "重新开启音效应恢复背景音乐"); sound.destroy(); assert.equal(backgroundEvents.at(-1), "destroy");
console.log("循环背景音乐、路径静音与纸牌数字提示校验通过");
